#!/usr/bin/env bash

RED=$(echo -en '\033[00;31m')
LBLUE=$(echo -en '\033[01;34m')
YELLOW=$(echo -en '\033[00;33m')
RESTORE=$(echo -en '\033[0m')

SHELL_PROFILE=$(. ./which-shell.sh)

COMMAND="${@}"
export COMMAND="$COMMAND"

function list_namespaces() {
  cat ~/.kube/plugins/jordanwilson230/config/namespaces
}

function list_clusters() {
  cat ~/.kube/plugins/jordanwilson230/config/clusters
}

### Description and usage
function description() {
    echo -e "\n${LBLUE}Description:\n   This plugin intercepts kubectl commands and, based on the arguments issued, \
will trigger an alert prompt\n   requiring the user to acknowledge they are operating in an important namespace (i.e., production).\n
    \n - To add a namespace that will trigger the prompt, run the following:\n\tkubectl prompt add [-n namespace] MY_NAMESPACE
    \n - To add a cluster that will trigger the prompt, run the following:\n\tkubectl prompt add [-c cluster] MY_CLUSTER
    \n - To list your flagged environments, run:\n\tkubectl prompt list
    \n - To clear your flagged environments, run:\n\tkubectl prompt remove${RESTORE}"
    exit 0
}

if [ $# -eq 0 ] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
    description
fi



### Add an environment to prompt
function add_usage() {
    echo -e "\nTo add a namespace or cluster that will trigger the prompt, run the command below.
Note: Accepts only one [-c] OR [-n] argument per command:\n
\t- kubectl prompt add [-c cluster] OR [-n namespace] NAME${RESTORE}\n"
    exit 0
}

function add_prompt() {
[ $# -eq 0 ] && add_usage
    while getopts ":c:n:" arg; do
        case $arg in
            c) # Add Cluster
               CLUSTER="${OPTARG}"
               ;;
            n) # Add Namespace
               NAMESPACE="${OPTARG}"
               ;;
            *)
               add_usage
               exit 1
               ;;
         esac
    done
    echo;
    if [[ "$NAMESPACE" ]]; then
        read -p "${YELLOW}* Add the namespace ${NAMESPACE} to prompt list [y/n]? ${RESTORE}" answer
        [[ "$answer" != "y" ]] && exit 0
        echo -e "\n${YELLOW}* Adding ${NAMESPACE} to namespaces in ~/.kube/plugins/jordanwilson230/config/namespaces\n${RESTORE}"
        echo $NAMESPACE >> ~/.kube/plugins/jordanwilson230/config/namespaces
    elif [[ "$CLUSTER" ]]; then
        read -p "${YELLOW}* Add the cluster ${CLUSTER} to prompt list [y/n]? ${RESTORE}" answer
        [[ "$answer" != "y" ]] && exit 0
        echo -e "\n${YELLOW}* Adding ${CLUSTER} to clusters in ~/.kube/plugins/jordanwilson230/config/clusters\n${RESTORE}"
        echo $CLUSTER >> ~/.kube/plugins/jordanwilson230/config/clusters
    fi
}



### Clear prompt list
function remove_prompt() {
    echo "" > ~/.kube/plugins/jordanwilson230/config/namespaces
    echo "" > ~/.kube/plugins/jordanwilson230/config/clusters
    exit 0
}



### List flagged environments
function list_prompt() {
  echo -e "\n${YELLOW}CLUSTERS: $(list_clusters)\nNAMESPACES: $(list_namespaces)${RESTORE}\n"
  exit 0
}


### Prompt user if running in a flagged envirinment
function prompt() {
    clear; echo -e "${RED}#################################################################################
\t*** You are operating in a flagged environment: ${NAMESPACE}${CLUSTER} ***
#################################################################################${RESTORE}\n
${YELLOW}Command: ${COMMAND}\n${RESTORE}"
    read -p "${RED}Proceed [yes/no]?${RESTORE} " answer
    echo -e "\n\n"
    [[ "$answer" != "yes" ]] && exit 1
    exit 0
}


# Skip checks if user has not assigned any (using kubectl prompt add [-n namespace OR -c cluster]
if [[ ! -z $(list_namespaces) ]] || [[ ! -z $(list_clusters) ]]; then
  # Only prompt when the command would cause the state of the env to change.
    echo "$@" | grep "deploy\|create\|apply\|set \|delete\|scale " 1>/dev/null
    if [ $? -eq 0 ]; then
        NAMESPACE=$(kubectl config view --template='{{ range .contexts }}{{ if eq .name "'$(kubectl config current-context)'" }}{{ .context.namespace }}{{ end }}{{ end }}')
        CLUSTER=$(kubectl config view --template='{{ range .contexts }}{{ if eq .name "'$(kubectl config current-context)'" }}{{ .context.cluster }}{{ end }}{{ end }}')
        if [[ $(list_namespaces) =~ "$NAMESPACE" ]]; then
            CLUSTER=''
            prompt "$NAMESPACE"
        elif [[ $(list_clusters) =~ "$CLUSTER" ]]; then
            NAMESPACE=''
            prompt "$CLUSTER"
        fi
    fi
fi


case "$1" in
    "add") add_prompt ${@/$1/} ;;
    "remove") remove_prompt ${COMMAND};;
    "list") list_prompt ;;
    *) exit 0 ;;
esac
